### ISSUE TITLE
An integer is required.

### ISSUE THREAD

**Issue by TGORonin** [billy-osullivan/alien_motion_tracker#1]
I get error that integer is required, (got type float)
Line 451 and line 322 ValueError: with greater then ellipse radius.  The 0.5236,   2.618,4

//i try on tv creen. Have only 2 buttons connected: SW1 SW2 to try demo.

**Comment by wolfgangrumpf** [comment]
I can confirm that the integer error happens on the 4" square screen as well:

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/wolfgang/motion_tracker.py:322: DeprecationWarning: an integer is required
 (got type float).  Implicit conversion to integers using __int__ is deprecated,
 and may be removed in a future version of Python.
  pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236,
2.618,4)
Traceback (most recent call last):
  File "/home/wolfgang/motion_tracker.py", line 451, in <module>
    main()
  File "/home/wolfgang/motion_tracker.py", line 322, in main
    pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236
, 2.618,4)
ValueError: width greater than ellipse radius

**Comment by jehutting** [comment]
BIlly is probably using pygame 2.0.

For pygame 1.9.6 usage you need to change the code as follows:

```
diff --git a/alien_motion_tracker_working.py b/alien_motion_tracker_working.py
index 5e87725..e3cf0b4 100644
--- a/alien_motion_tracker_working.py
+++ b/alien_motion_tracker_working.py
@@ -229,8 +229,10 @@ def main():
        sound = 1
        arc_x = 360
        arc_y = 590
-       arc_width = 0.1
-       arc_height = 0.1
+       ARC_WIDTH = 9.1
+       ARC_HEIGHT = 2*5.75
+       arc_width = ARC_WIDTH
+       arc_height = ARC_HEIGHT
 
        pygame.init()
        # hide mouse icon
@@ -319,7 +321,7 @@ def main():
 
                # draw the arc animation
                if loop_counter <=75:
-                       pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236, 2.618,4)
+                       pygame.draw.arc(screen, WHITE, [int(arc_x), int(arc_y), int(arc_width), int(arc_height)], 0.5236, 2.618,4)
                        arc_x = arc_x - 4.45
                        arc_y = arc_y - 6.58
                        arc_width = arc_width + 9.1
@@ -328,8 +330,8 @@ def main():
                        loop_counter = 1
                        arc_x = 360
                        arc_y = 590
-                       arc_width = 0.1
-                       arc_height = 0.1
+                       arc_width = ARC_WIDTH
+                       arc_height = ARC_HEIGHT
 
                # mode 1 is a demo mode that will output data without
                # using any sensors

```
The explicit casting to int(eger) in de `pygame.draw.arc` call is to get rid of 
```
alien_motion_tracker_working.py:<line>: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236, 2.618, 4)
```

**Comment by TGORonin** [comment]
Hi, I got it working thx, just missing the resistors as its so damn hard to buy them in sweden. Els you buy a 400 pack of diffrent once! So sad..



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Jozef Hutting ***@***.***>
Datum: 2022-10-23 08:49 (GMT+01:00)
Till: billy-osullivan/alien_motion_tracker ***@***.***>
Kopia: TGORonin ***@***.***>, Author ***@***.***>
Ämne: Re: [billy-osullivan/alien_motion_tracker] An integer is required. (Issue #1)


BIlly is probably using pygame 2.0.

For pygame 1.9.6 usage you need to change the code as follows:

diff --git a/alien_motion_tracker_working.py b/alien_motion_tracker_working.py
index 5e87725..e3cf0b4 100644
--- a/alien_motion_tracker_working.py
+++ b/alien_motion_tracker_working.py
@@ -229,8 +229,10 @@ def main():
        sound = 1
        arc_x = 360
        arc_y = 590
-       arc_width = 0.1
-       arc_height = 0.1
+       ARC_WIDTH = 9.1
+       ARC_HEIGHT = 2*5.75
+       arc_width = ARC_WIDTH
+       arc_height = ARC_HEIGHT

        pygame.init()
        # hide mouse icon
@@ -319,7 +321,7 @@ def main():

                # draw the arc animation
                if loop_counter <=75:
-                       pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236, 2.618,4)
+                       pygame.draw.arc(screen, WHITE, [int(arc_x), int(arc_y), int(arc_width), int(arc_height)], 0.5236, 2.618,4)
                        arc_x = arc_x - 4.45
                        arc_y = arc_y - 6.58
                        arc_width = arc_width + 9.1
@@ -328,8 +330,8 @@ def main():
                        loop_counter = 1
                        arc_x = 360
                        arc_y = 590
-                       arc_width = 0.1
-                       arc_height = 0.1
+                       arc_width = ARC_WIDTH
+                       arc_height = ARC_HEIGHT

                # mode 1 is a demo mode that will output data without
                # using any sensors



The explicit casting to int(eger) in de pygame.draw.arc call is to get rid of

alien_motion_tracker_working.py:<line>: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  pygame.draw.arc(screen, WHITE, [arc_x, arc_y, arc_width, arc_height], 0.5236, 2.618, 4)
